flag_management:
  default_rules: # the rules that will be followed for any flag added, generally
    carryforward: true
    statuses:
      - name_prefix: project-
        type: project
        target: auto
      - name_prefix: patch-
        type: patch
        target: auto
comment:
  show_carryforward_flags: true