name: Publish python package to TestPyPI

on: 
  push:
    branches: ["master"]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0 
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install pypa/build
        run: |
          python -m pip install poetry poetry-dynamic-versioning
      - name: Use Node.js 17.x
        uses: actions/setup-node@v1
        with:
          node-version: 17.x
      - name: Install dependencies
        run: yarn install --frozen-lockfile
        working-directory: ./frontend
      - name: Build frontend
        run: yarn build --outDir ../upnpavcontrol/web/static
        working-directory: ./frontend
      - name: Build a binary wheel and a source tarball
        run: |
          poetry build
      - name: Publish 📦 to Test PyPI
        run: |
          poetry config repositories.testpypi https://test.pypi.org/legacy/
          poetry config pypi-token.testpypi ${{ secrets.TEST_PYPI_API_TOKEN }}
          poetry publish -r testpypi